name: Benchmarks

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: bench-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  spsc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Run spsc benchmarks
        run: cargo bench spsc | tee spsc.txt

      - name: Publish / Compare benchmarks
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: spsc
          tool: cargo
          output-file-path: spsc.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}

          auto-push: ${{ github.event_name == 'push' }}

          comment-always: true
          fail-on-alert: false
